name       : inotify-tools
version    : 3.20.2.2
release    : 4
source     :
    - https://github.com/inotify-tools/inotify-tools/releases/download/3.20.2.2/inotify-tools-3.20.2.2.tar.gz : c5b018567814ea555d716f518b6e3ae243c733f7bd3e8585d81748a6da286f3c
homepage   : https://github.com/rvoicilas/inotify-tools/wiki
license    : GPL-2.0-or-later
component  : system.base
summary    : inotify-tools is a C library and a set of command-line programs for Linux providing a simple interface to inotify.
description: |
    inotify-tools is a set of command-line programs for Linux providing a simple  interface to inotify. These programs can be used to monitor and act upon filesystem events. inotify-tools consists of two utilities:

    inotifywait simply blocks for inotify events, making it appropriate for use in shell scripts.

    inotifywatch collects filesystem usage statistics and outputs counts of each inotify event.

setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
