name       : inotify-tools
version    : 3.20.11.0
release    : 5
source     :
    - https://github.com/inotify-tools/inotify-tools/archive/refs/tags/3.20.11.0.tar.gz : 58a3cde89e4a5111a87ac16b56b06a8f885460fca0aea51b69c856ce30a37a14
homepage   : https://github.com/rvoicilas/inotify-tools/wiki
license    : GPL-2.0-or-later
component  : system.base
summary    : inotify-tools is a C library and a set of command-line programs for Linux providing a simple interface to inotify.
description: |
    inotify-tools is a set of command-line programs for Linux providing a simple  interface to inotify. These programs can be used to monitor and act upon filesystem events. inotify-tools consists of two utilities:

    inotifywait simply blocks for inotify events, making it appropriate for use in shell scripts.

    inotifywatch collects filesystem usage statistics and outputs counts of each inotify event.

setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
