name       : inotify-tools
version    : 3.20.1
release    : 3
source     :
    - https://github.com/rvoicilas/inotify-tools/archive/3.20.1.tar.gz : a433cc1dedba851078276db69b0e97f9fe41e4ba3336d2971adfca4b3a6242ac
homepage   : https://github.com/rvoicilas/inotify-tools/wiki
license    :
    - GPLv2
component  : system.base
summary    : inotify-tools is a C library and a set of command-line programs for Linux providing a simple interface to inotify.
description: |
    command-line programs providing a simple interface to inotify. inotify-tools is a set of command-line programs for Linux providing a simple  interface to inotify. These programs can be used to monitor and act upon filesystem events. inotify-tools consists of two utilities:

    inotifywait simply blocks for inotify events, making it appropriate for use in shell scripts.

    inotifywatch collects filesystem usage statistics and outputs counts of each inotify event.

setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
