name        : inotify-tools
version     : 3.14
release     : 2
source      :
    - http://cloud.github.com/downloads/rvoicilas/inotify-tools/inotify-tools-3.14.tar.gz : 222bcca8893d7bf8a1ce207fb39ceead5233b5015623d099392e95197676c92f
homepage    : https://github.com/rvoicilas/inotify-tools/wiki
license     :
    - GPLv2
component   : system.base
summary     : inotify-tools is a C library and a set of command-line programs for Linux providing a simple interface to inotify.
description : |
    command-line programs providing a simple interface to inotify. inotify-tools is a set of command-line programs for Linux providing a simple  interface to inotify. These programs can be used to monitor and act upon filesystem events. inotify-tools consists of two utilities:
    
    inotifywait simply blocks for inotify events, making it appropriate for use in shell scripts.
    
    inotifywatch collects filesystem usage statistics and outputs counts of each inotify event.
    
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
